-- MySQLens Database Initialization Script
-- Creates the schema for storing analysis results, recommendations, and audit logs

-- Create the mysqlens database if it doesn't exist
CREATE DATABASE IF NOT EXISTS mysqlens CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE mysqlens;

-- =============================================================================
-- CORE TABLES
-- =============================================================================

-- Stored database connections (encrypted credentials)
CREATE TABLE IF NOT EXISTS connections (
    id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
    name VARCHAR(100) NOT NULL,
    host VARCHAR(255) NOT NULL,
    port INT NOT NULL DEFAULT 3306,
    username VARCHAR(100) NOT NULL,
    password_encrypted TEXT NOT NULL,
    database_name VARCHAR(100),
    is_active BOOLEAN DEFAULT TRUE,
    last_connected_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_connection_name (name)
) ENGINE=InnoDB;

-- Query metrics captured from performance_schema
CREATE TABLE IF NOT EXISTS query_metrics (
    id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
    connection_id VARCHAR(36),
    query_hash VARCHAR(64) NOT NULL,
    query_text TEXT NOT NULL,
    schema_name VARCHAR(100),
    total_time_ms BIGINT NOT NULL DEFAULT 0,
    exec_count BIGINT NOT NULL DEFAULT 0,
    avg_time_ms DOUBLE NOT NULL DEFAULT 0,
    max_time_ms BIGINT DEFAULT 0,
    min_time_ms BIGINT DEFAULT 0,
    rows_examined BIGINT DEFAULT 0,
    rows_sent BIGINT DEFAULT 0,
    tmp_tables BIGINT DEFAULT 0,
    tmp_disk_tables BIGINT DEFAULT 0,
    full_scan_count BIGINT DEFAULT 0,
    sort_rows BIGINT DEFAULT 0,
    no_index_used BIGINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_query_hash (query_hash),
    INDEX idx_connection_id (connection_id),
    INDEX idx_total_time (total_time_ms DESC),
    INDEX idx_created_at (created_at),
    FOREIGN KEY (connection_id) REFERENCES connections(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- AI analysis results
CREATE TABLE IF NOT EXISTS analysis_results (
    id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
    query_hash VARCHAR(64) NOT NULL,
    query_text TEXT NOT NULL,
    execution_plan JSON,
    analysis_summary TEXT,
    performance_score INT CHECK (performance_score >= 0 AND performance_score <= 100),
    bottleneck_type VARCHAR(50),
    bottleneck_details JSON,
    llm_provider VARCHAR(50),
    llm_model VARCHAR(100),
    prompt_tokens INT,
    completion_tokens INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_query_hash (query_hash),
    INDEX idx_performance_score (performance_score),
    INDEX idx_bottleneck_type (bottleneck_type),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB;

-- Recommendations generated by AI or rules engine
CREATE TABLE IF NOT EXISTS recommendations (
    id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
    query_hash VARCHAR(64) NOT NULL,
    analysis_id VARCHAR(36),
    recommendation_type ENUM('INDEX', 'REWRITE', 'SCHEMA', 'CONFIGURATION', 'ADVISORY') NOT NULL,
    category VARCHAR(50),
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    sql_fix TEXT,
    rollback_sql TEXT,
    original_sql TEXT,
    estimated_improvement_percent INT,
    confidence_score INT CHECK (confidence_score >= 0 AND confidence_score <= 100),
    risk_level ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL') DEFAULT 'MEDIUM',
    status ENUM('pending', 'applied', 'rejected', 'rolled_back') DEFAULT 'pending',
    applied BOOLEAN DEFAULT FALSE,
    applied_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_query_hash (query_hash),
    INDEX idx_recommendation_type (recommendation_type),
    INDEX idx_status (status),
    INDEX idx_applied (applied),
    INDEX idx_risk_level (risk_level),
    INDEX idx_created_at (created_at),
    FOREIGN KEY (analysis_id) REFERENCES analysis_results(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Index analysis and recommendations
CREATE TABLE IF NOT EXISTS index_analysis (
    id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
    connection_id VARCHAR(36),
    schema_name VARCHAR(100) NOT NULL,
    table_name VARCHAR(100) NOT NULL,
    index_name VARCHAR(100) NOT NULL,
    index_type VARCHAR(50),
    columns JSON,
    size_bytes BIGINT DEFAULT 0,
    cardinality BIGINT DEFAULT 0,
    usage_count BIGINT DEFAULT 0,
    last_used_at TIMESTAMP NULL,
    days_unused INT DEFAULT 0,
    is_duplicate BOOLEAN DEFAULT FALSE,
    duplicate_of VARCHAR(100),
    recommendation ENUM('KEEP', 'DROP', 'MODIFY', 'MERGE') DEFAULT 'KEEP',
    recommendation_reason TEXT,
    estimated_savings_mb DOUBLE DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_table (schema_name, table_name),
    INDEX idx_recommendation (recommendation),
    INDEX idx_days_unused (days_unused),
    INDEX idx_connection (connection_id),
    FOREIGN KEY (connection_id) REFERENCES connections(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Audit log for all actions
CREATE TABLE IF NOT EXISTS audit_logs (
    id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
    action_type ENUM(
        'CONNECTION_CREATED', 'CONNECTION_DELETED', 'CONNECTION_UPDATED',
        'ANALYSIS_RUN', 'RECOMMENDATION_CREATED', 'RECOMMENDATION_APPLIED',
        'RECOMMENDATION_REJECTED', 'RECOMMENDATION_ROLLED_BACK',
        'INDEX_CREATED', 'INDEX_DROPPED', 'QUERY_REWRITTEN',
        'HEALTH_SCAN', 'SETTINGS_CHANGED'
    ) NOT NULL,
    user_identifier VARCHAR(100),
    resource_type VARCHAR(50),
    resource_id VARCHAR(36),
    before_state JSON,
    after_state JSON,
    details JSON,
    ip_address VARCHAR(45),
    user_agent TEXT,
    status ENUM('SUCCESS', 'FAILURE', 'PENDING') DEFAULT 'SUCCESS',
    error_message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_action_type (action_type),
    INDEX idx_resource (resource_type, resource_id),
    INDEX idx_created_at (created_at),
    INDEX idx_status (status)
) ENGINE=InnoDB;

-- Health scan results
CREATE TABLE IF NOT EXISTS health_scans (
    id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
    connection_id VARCHAR(36),
    overall_score INT CHECK (overall_score >= 0 AND overall_score <= 100),
    performance_score INT,
    security_score INT,
    configuration_score INT,
    index_score INT,
    scan_duration_ms INT,
    issues_found INT DEFAULT 0,
    warnings_found INT DEFAULT 0,
    details JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_connection (connection_id),
    INDEX idx_overall_score (overall_score),
    INDEX idx_created_at (created_at),
    FOREIGN KEY (connection_id) REFERENCES connections(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- LLM cache for response caching
CREATE TABLE IF NOT EXISTS llm_cache (
    cache_key VARCHAR(64) PRIMARY KEY,
    prompt_hash VARCHAR(64) NOT NULL,
    response TEXT NOT NULL,
    llm_provider VARCHAR(50),
    llm_model VARCHAR(100),
    tokens_used INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP,
    INDEX idx_prompt_hash (prompt_hash),
    INDEX idx_expires_at (expires_at)
) ENGINE=InnoDB;

-- Application settings
CREATE TABLE IF NOT EXISTS settings (
    `key` VARCHAR(100) PRIMARY KEY,
    value JSON NOT NULL,
    description TEXT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- =============================================================================
-- VIEWS
-- =============================================================================

-- Top slow queries view
CREATE OR REPLACE VIEW v_slow_queries AS
SELECT 
    qm.id,
    qm.query_hash,
    LEFT(qm.query_text, 200) as query_preview,
    qm.total_time_ms,
    qm.exec_count,
    qm.avg_time_ms,
    qm.rows_examined,
    qm.full_scan_count,
    qm.no_index_used,
    qm.created_at,
    (SELECT COUNT(*) FROM recommendations r WHERE r.query_hash = qm.query_hash AND r.status = 'pending') as pending_recommendations
FROM query_metrics qm
WHERE qm.avg_time_ms > 100  -- Queries averaging over 100ms
ORDER BY qm.total_time_ms DESC;

-- Recent recommendations view
CREATE OR REPLACE VIEW v_recent_recommendations AS
SELECT 
    r.id,
    r.query_hash,
    r.recommendation_type,
    r.title,
    r.risk_level,
    r.confidence_score,
    r.status,
    r.created_at,
    ar.performance_score as original_performance_score
FROM recommendations r
LEFT JOIN analysis_results ar ON r.analysis_id = ar.id
WHERE r.created_at >= DATE_SUB(NOW(), INTERVAL 24 HOUR)
ORDER BY r.created_at DESC;

-- Index health summary view
CREATE OR REPLACE VIEW v_index_health AS
SELECT 
    schema_name,
    table_name,
    COUNT(*) as total_indexes,
    SUM(CASE WHEN recommendation = 'DROP' THEN 1 ELSE 0 END) as unused_indexes,
    SUM(CASE WHEN is_duplicate = TRUE THEN 1 ELSE 0 END) as duplicate_indexes,
    SUM(size_bytes) as total_size_bytes,
    SUM(estimated_savings_mb) as potential_savings_mb
FROM index_analysis
GROUP BY schema_name, table_name;

-- =============================================================================
-- DEFAULT DATA
-- =============================================================================

-- Insert default settings
INSERT INTO settings (`key`, value, description) VALUES
('llm_provider', '"ollama"', 'Default LLM provider (ollama, openai, gemini)'),
('llm_model', '"llama3.2:latest"', 'Default LLM model'),
('cache_ttl_seconds', '3600', 'LLM cache TTL in seconds'),
('slow_query_threshold_ms', '100', 'Threshold for slow query detection in milliseconds'),
('auto_analyze', 'true', 'Automatically analyze new slow queries'),
('max_recommendations_per_query', '5', 'Maximum recommendations to generate per query')
ON DUPLICATE KEY UPDATE updated_at = CURRENT_TIMESTAMP;

-- =============================================================================
-- CLEANUP EVENTS (optional - requires EVENT scheduler)
-- =============================================================================

-- Clean up old cache entries (run daily)
-- Note: Requires EVENT_SCHEDULER to be enabled
-- SET GLOBAL event_scheduler = ON;

DELIMITER //

CREATE EVENT IF NOT EXISTS cleanup_expired_cache
ON SCHEDULE EVERY 1 DAY
DO
BEGIN
    DELETE FROM llm_cache WHERE expires_at < NOW();
END//

CREATE EVENT IF NOT EXISTS cleanup_old_audit_logs
ON SCHEDULE EVERY 1 WEEK
DO
BEGIN
    -- Keep audit logs for 90 days
    DELETE FROM audit_logs WHERE created_at < DATE_SUB(NOW(), INTERVAL 90 DAY);
END//

DELIMITER ;

-- =============================================================================
-- DONE
-- =============================================================================

SELECT 'MySQLens database initialized successfully!' AS status;
SELECT 
    (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'mysqlens') AS tables_created,
    (SELECT COUNT(*) FROM information_schema.views WHERE table_schema = 'mysqlens') AS views_created;
